# Generated by Django 6.0.5 on 2026-06-08 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHeadType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head_type_name', models.CharField(max_length=50, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lkp_account_head_type',
            },
        ),
        migrations.CreateModel(
            name='CabinWardDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabin_ward_no', models.CharField(max_length=100)),
                ('cabin_ward_charge', models.IntegerField(blank=True, null=True)),
                ('service_charge', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('final_charge', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lkp_cabin_ward_details',
            },
        ),
        migrations.CreateModel(
            name='DischargedRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_of_admission', models.CharField(blank=True, max_length=200, null=True)),
                ('admit_doctor_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cabin_ward_no', models.CharField(blank=True, max_length=100, null=True)),
                ('important_notes', models.TextField(blank=True, null=True)),
                ('admit_date', models.DateTimeField(blank=True, null=True)),
                ('provided_discount', models.IntegerField(blank=True, null=True)),
                ('total_discharge_amount', models.IntegerField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_by', models.CharField(blank=True, max_length=100, null=True)),
                ('discharge_status', models.CharField(blank=True, max_length=20, null=True)),
                ('discharge_due_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tbl_discharge_records',
            },
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lkp_doctor_details',
            },
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_group_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lkp_test_group',
            },
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head_code', models.CharField(max_length=20, unique=True)),
                ('account_head_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('account_head_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_model.accountheadtype')),
            ],
            options={
                'db_table': 'lkp_account_head',
            },
        ),
        migrations.CreateModel(
            name='AdmitPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_of_admission', models.CharField(blank=True, max_length=200, null=True)),
                ('important_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Admission date and time', null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cabin_ward_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='app_model.cabinwarddetails')),
                ('admit_doctor_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='app_model.doctordetails')),
            ],
            options={
                'db_table': 'tbl_admit_patients',
            },
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_charge', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('test_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_model.testgroup')),
            ],
            options={
                'db_table': 'lkp_test_details',
            },
        ),
        migrations.CreateModel(
            name='TestsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('Admitted', 'Admitted'), ('Non-Admit', 'Non-Admit')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('provided_discount', models.IntegerField(blank=True, null=True)),
                ('total_test_amount', models.IntegerField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('admitted_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_records', to='app_model.admitpatient')),
                ('test_doctor_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_records', to='app_model.doctordetails')),
            ],
            options={
                'db_table': 'tbl_tests_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestsRecordItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_amount', models.IntegerField(blank=True, null=True)),
                ('tests_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_model.testsrecord')),
            ],
            options={
                'db_table': 'tbl_tests_record_items',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_category', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('user_role', models.CharField(blank=True, default='user', max_length=100, null=True)),
                ('user_status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('account_head_type', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_model.accounthead')),
            ],
            options={
                'db_table': 'tbl_voucher_details',
            },
        ),
    ]
